// curl 'https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=false&sort_nulls_last=true&sort=-contribution_receipt_date&per_page=10&committee_id=C00498121&two_year_transaction_period=2018&is_individual=true' -H 'Origin: https://www.fec.gov' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: https://www.fec.gov/data/committee/C00498121/?cycle=2018&tab=raising' -H 'Connection: keep-alive' --compressed

{
	"api_version": "1.0",
	"results": [{
		"contributor_occupation": "CHAIRMAN & CEO - RETIRED",
		"contributor_aggregate_ytd": 500.0,
		"memo_code": null,
		"candidate_office": null,
		"contributor_last_name": "MAYS",
		"file_number": 1298625,
		"recipient_committee_type": "H",
		"amendment_indicator": "A",
		"conduit_committee_street2": null,
		"memo_code_full": null,
		"committee_id": "C00498121",
		"contributor_middle_name": "LOWRY",
		"two_year_transaction_period": 2018,
		"contributor_zip": "78209",
		"committee_name": null,
		"conduit_committee_state": null,
		"link_id": 4120620181620450055,
		"memoed_subtotal": false,
		"contributor_prefix": "MR.",
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"receipt_type": "15",
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"candidate_middle_name": null,
		"fec_election_type_desc": "GENERAL",
		"line_number_label": "Contributions From Individuals\/Persons Other Than Political Committees",
		"original_sub_id": null,
		"contributor": null,
		"memo_text": null,
		"back_reference_schedule_name": null,
		"conduit_committee_id": null,
		"contributor_id": null,
		"committee": {
			"organization_type": null,
			"street_1": "P.O. BOX 91061",
			"committee_type_full": "House",
			"candidate_ids": ["H2TX33040"],
			"filing_frequency": "Q",
			"designation_full": "Principal campaign committee",
			"street_2": null,
			"cycles": [2012, 2014, 2016, 2018, 2020],
			"party": "REP",
			"committee_id": "C00498121",
			"zip": "787091061",
			"designation": "P",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_type": "H",
			"organization_type_full": null,
			"treasurer_name": "FARMER, GARY S.",
			"party_full": "REPUBLICAN PARTY",
			"city": "AUSTIN",
			"cycle": 2018,
			"state": "TX",
			"state_full": "Texas"
		},
		"fec_election_year": "2018",
		"contributor_city": "SAN ANTONIO",
		"entity_type_desc": "INDIVIDUAL",
		"candidate_suffix": null,
		"image_number": "201812069134816142",
		"conduit_committee_city": null,
		"candidate_last_name": null,
		"transaction_id": "SA11AI.11152",
		"candidate_name": null,
		"receipt_type_full": "POSTMARKED AND DATED BEFORE 11\/06\/18",
		"candidate_office_district": null,
		"contributor_street_2": null,
		"candidate_prefix": null,
		"contributor_street_1": "250 W NOTTINGHAM DR STE 400",
		"candidate_office_full": null,
		"is_individual": true,
		"report_year": 2018,
		"increased_limit": null,
		"contributor_suffix": null,
		"candidate_office_state": null,
		"contribution_receipt_amount": 500.0,
		"sub_id": "4121920181622525060",
		"receipt_type_desc": "CONTRIBUTION",
		"contributor_first_name": "L.",
		"unused_contbr_id": null,
		"back_reference_transaction_id": null,
		"contributor_state": "TX",
		"entity_type": "IND",
		"contribution_receipt_date": "2018-11-09T00:00:00",
		"conduit_committee_street1": null,
		"national_committee_nonfederal_account": null,
		"candidate_id": null,
		"candidate_first_name": null,
		"conduit_committee_name": null,
		"election_type_full": null,
		"contributor_employer": "CLEAR CHANNEL COMMUNICATIONS, INC.",
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"report_type": "30G",
		"schedule_type": "SA",
		"amendment_indicator_desc": "ADD",
		"line_number": "11AI",
		"load_date": "2018-12-20T02:51:49.663000+00:00",
		"donor_committee_name": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816142",
		"contributor_name": "MAYS, L. LOWRY MR."
	}, {
		"contributor_occupation": "OIL & GAS",
		"contributor_aggregate_ytd": 2700.0,
		"memo_code": "X",
		"candidate_office": null,
		"contributor_last_name": "CUNNINGHAM",
		"file_number": 1298625,
		"recipient_committee_type": "H",
		"amendment_indicator": "A",
		"conduit_committee_street2": null,
		"memo_code_full": null,
		"committee_id": "C00498121",
		"contributor_middle_name": null,
		"two_year_transaction_period": 2018,
		"contributor_zip": "76087",
		"committee_name": null,
		"conduit_committee_state": null,
		"link_id": 4120620181620450055,
		"memoed_subtotal": true,
		"contributor_prefix": "MR.",
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"receipt_type": "15J",
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"candidate_middle_name": null,
		"fec_election_type_desc": "GENERAL",
		"line_number_label": "Transfers from authorized committees",
		"original_sub_id": null,
		"contributor": null,
		"memo_text": null,
		"back_reference_schedule_name": "SA12",
		"conduit_committee_id": null,
		"contributor_id": null,
		"committee": {
			"organization_type": null,
			"street_1": "P.O. BOX 91061",
			"committee_type_full": "House",
			"candidate_ids": ["H2TX33040"],
			"filing_frequency": "Q",
			"designation_full": "Principal campaign committee",
			"street_2": null,
			"cycles": [2012, 2014, 2016, 2018, 2020],
			"party": "REP",
			"committee_id": "C00498121",
			"zip": "787091061",
			"designation": "P",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_type": "H",
			"organization_type_full": null,
			"treasurer_name": "FARMER, GARY S.",
			"party_full": "REPUBLICAN PARTY",
			"city": "AUSTIN",
			"cycle": 2018,
			"state": "TX",
			"state_full": "Texas"
		},
		"fec_election_year": "2018",
		"contributor_city": "HUDSON OAKS",
		"entity_type_desc": "INDIVIDUAL",
		"candidate_suffix": null,
		"image_number": "201812069134816169",
		"conduit_committee_city": null,
		"candidate_last_name": null,
		"transaction_id": "SA12.11187.86",
		"candidate_name": null,
		"receipt_type_full": "JOINT FUNDRAISER - ROGER FOR CONGRESS VICTORY FUND",
		"candidate_office_district": null,
		"contributor_street_2": null,
		"candidate_prefix": null,
		"contributor_street_1": "4901 E BANKHEAD HWY",
		"candidate_office_full": null,
		"is_individual": true,
		"report_year": 2018,
		"increased_limit": null,
		"contributor_suffix": null,
		"candidate_office_state": null,
		"contribution_receipt_amount": 2700.0,
		"sub_id": "4121920181622525139",
		"receipt_type_desc": "MEMO (FILER'S % OF CONTRIBUTION GIVEN TO JOIN",
		"contributor_first_name": "BRAD",
		"unused_contbr_id": null,
		"back_reference_transaction_id": "SA12.11187",
		"contributor_state": "TX",
		"entity_type": "IND",
		"contribution_receipt_date": "2018-11-06T00:00:00",
		"conduit_committee_street1": null,
		"national_committee_nonfederal_account": null,
		"candidate_id": null,
		"candidate_first_name": null,
		"conduit_committee_name": null,
		"election_type_full": null,
		"contributor_employer": "FOUR SEVENS OIL CO.",
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"report_type": "30G",
		"schedule_type": "SA",
		"amendment_indicator_desc": "ADD",
		"line_number": "12",
		"load_date": "2018-12-20T02:51:49.668000+00:00",
		"donor_committee_name": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816169",
		"contributor_name": "CUNNINGHAM, BRAD MR."
	}, {
		"contributor_occupation": "PARTNER",
		"contributor_aggregate_ytd": 2700.0,
		"memo_code": "X",
		"candidate_office": null,
		"contributor_last_name": "LOWE",
		"file_number": 1298625,
		"recipient_committee_type": "H",
		"amendment_indicator": "A",
		"conduit_committee_street2": null,
		"memo_code_full": null,
		"committee_id": "C00498121",
		"contributor_middle_name": null,
		"two_year_transaction_period": 2018,
		"contributor_zip": "76114",
		"committee_name": null,
		"conduit_committee_state": null,
		"link_id": 4120620181620450055,
		"memoed_subtotal": true,
		"contributor_prefix": "MR.",
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"receipt_type": "15J",
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"candidate_middle_name": null,
		"fec_election_type_desc": "GENERAL",
		"line_number_label": "Transfers from authorized committees",
		"original_sub_id": null,
		"contributor": null,
		"memo_text": null,
		"back_reference_schedule_name": "SA12",
		"conduit_committee_id": null,
		"contributor_id": null,
		"committee": {
			"organization_type": null,
			"street_1": "P.O. BOX 91061",
			"committee_type_full": "House",
			"candidate_ids": ["H2TX33040"],
			"filing_frequency": "Q",
			"designation_full": "Principal campaign committee",
			"street_2": null,
			"cycles": [2012, 2014, 2016, 2018, 2020],
			"party": "REP",
			"committee_id": "C00498121",
			"zip": "787091061",
			"designation": "P",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_type": "H",
			"organization_type_full": null,
			"treasurer_name": "FARMER, GARY S.",
			"party_full": "REPUBLICAN PARTY",
			"city": "AUSTIN",
			"cycle": 2018,
			"state": "TX",
			"state_full": "Texas"
		},
		"fec_election_year": "2018",
		"contributor_city": "WESTWORTH VILLAGE",
		"entity_type_desc": "INDIVIDUAL",
		"candidate_suffix": null,
		"image_number": "201812069134816169",
		"conduit_committee_city": null,
		"candidate_last_name": null,
		"transaction_id": "SA12.11187.85",
		"candidate_name": null,
		"receipt_type_full": "JOINT FUNDRAISER - ROGER FOR CONGRESS VICTORY FUND",
		"candidate_office_district": null,
		"contributor_street_2": null,
		"candidate_prefix": null,
		"contributor_street_1": "701 CINNABAR CT",
		"candidate_office_full": null,
		"is_individual": true,
		"report_year": 2018,
		"increased_limit": null,
		"contributor_suffix": null,
		"candidate_office_state": null,
		"contribution_receipt_amount": 2700.0,
		"sub_id": "4121920181622525138",
		"receipt_type_desc": "MEMO (FILER'S % OF CONTRIBUTION GIVEN TO JOIN",
		"contributor_first_name": "DICK",
		"unused_contbr_id": null,
		"back_reference_transaction_id": "SA12.11187",
		"contributor_state": "TX",
		"entity_type": "IND",
		"contribution_receipt_date": "2018-11-06T00:00:00",
		"conduit_committee_street1": null,
		"national_committee_nonfederal_account": null,
		"candidate_id": null,
		"candidate_first_name": null,
		"conduit_committee_name": null,
		"election_type_full": null,
		"contributor_employer": "FOUR SEVENS OIL",
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"report_type": "30G",
		"schedule_type": "SA",
		"amendment_indicator_desc": "ADD",
		"line_number": "12",
		"load_date": "2018-12-20T02:51:49.668000+00:00",
		"donor_committee_name": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816169",
		"contributor_name": "LOWE, DICK MR."
	}, {
		"contributor_occupation": "RETIRED",
		"contributor_aggregate_ytd": 750.0,
		"memo_code": null,
		"candidate_office": null,
		"contributor_last_name": "MOONEY",
		"file_number": 1298625,
		"recipient_committee_type": "H",
		"amendment_indicator": "A",
		"conduit_committee_street2": null,
		"memo_code_full": null,
		"committee_id": "C00498121",
		"contributor_middle_name": null,
		"two_year_transaction_period": 2018,
		"contributor_zip": "78703",
		"committee_name": null,
		"conduit_committee_state": null,
		"link_id": 4120620181620450055,
		"memoed_subtotal": false,
		"contributor_prefix": "MRS.",
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"receipt_type": "15",
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"candidate_middle_name": null,
		"fec_election_type_desc": "GENERAL",
		"line_number_label": "Contributions From Individuals\/Persons Other Than Political Committees",
		"original_sub_id": null,
		"contributor": null,
		"memo_text": null,
		"back_reference_schedule_name": null,
		"conduit_committee_id": null,
		"contributor_id": null,
		"committee": {
			"organization_type": null,
			"street_1": "P.O. BOX 91061",
			"committee_type_full": "House",
			"candidate_ids": ["H2TX33040"],
			"filing_frequency": "Q",
			"designation_full": "Principal campaign committee",
			"street_2": null,
			"cycles": [2012, 2014, 2016, 2018, 2020],
			"party": "REP",
			"committee_id": "C00498121",
			"zip": "787091061",
			"designation": "P",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_type": "H",
			"organization_type_full": null,
			"treasurer_name": "FARMER, GARY S.",
			"party_full": "REPUBLICAN PARTY",
			"city": "AUSTIN",
			"cycle": 2018,
			"state": "TX",
			"state_full": "Texas"
		},
		"fec_election_year": "2018",
		"contributor_city": "AUSTIN",
		"entity_type_desc": "INDIVIDUAL",
		"candidate_suffix": null,
		"image_number": "201812069134816143",
		"conduit_committee_city": null,
		"candidate_last_name": null,
		"transaction_id": "SA11AI.11158",
		"candidate_name": null,
		"receipt_type_full": null,
		"candidate_office_district": null,
		"contributor_street_2": null,
		"candidate_prefix": null,
		"contributor_street_1": "2546 SCENIC DR",
		"candidate_office_full": null,
		"is_individual": true,
		"report_year": 2018,
		"increased_limit": null,
		"contributor_suffix": null,
		"candidate_office_state": null,
		"contribution_receipt_amount": 750.0,
		"sub_id": "4121920181622525063",
		"receipt_type_desc": "CONTRIBUTION",
		"contributor_first_name": "KATHERINE",
		"unused_contbr_id": null,
		"back_reference_transaction_id": null,
		"contributor_state": "TX",
		"entity_type": "IND",
		"contribution_receipt_date": "2018-11-06T00:00:00",
		"conduit_committee_street1": null,
		"national_committee_nonfederal_account": null,
		"candidate_id": null,
		"candidate_first_name": null,
		"conduit_committee_name": null,
		"election_type_full": null,
		"contributor_employer": "RETIRED",
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"report_type": "30G",
		"schedule_type": "SA",
		"amendment_indicator_desc": "ADD",
		"line_number": "11AI",
		"load_date": "2018-12-20T02:51:49.663000+00:00",
		"donor_committee_name": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816143",
		"contributor_name": "MOONEY, KATHERINE MRS."
	}, {
		"contributor_occupation": "MANAGER",
		"contributor_aggregate_ytd": 250.0,
		"memo_code": null,
		"candidate_office": null,
		"contributor_last_name": "MOONEY",
		"file_number": 1298625,
		"recipient_committee_type": "H",
		"amendment_indicator": "A",
		"conduit_committee_street2": null,
		"memo_code_full": null,
		"committee_id": "C00498121",
		"contributor_middle_name": null,
		"two_year_transaction_period": 2018,
		"contributor_zip": "78703",
		"committee_name": null,
		"conduit_committee_state": null,
		"link_id": 4120620181620450055,
		"memoed_subtotal": false,
		"contributor_prefix": "MR.",
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"receipt_type": "15",
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"candidate_middle_name": null,
		"fec_election_type_desc": "GENERAL",
		"line_number_label": "Contributions From Individuals\/Persons Other Than Political Committees",
		"original_sub_id": null,
		"contributor": null,
		"memo_text": null,
		"back_reference_schedule_name": null,
		"conduit_committee_id": null,
		"contributor_id": null,
		"committee": {
			"organization_type": null,
			"street_1": "P.O. BOX 91061",
			"committee_type_full": "House",
			"candidate_ids": ["H2TX33040"],
			"filing_frequency": "Q",
			"designation_full": "Principal campaign committee",
			"street_2": null,
			"cycles": [2012, 2014, 2016, 2018, 2020],
			"party": "REP",
			"committee_id": "C00498121",
			"zip": "787091061",
			"designation": "P",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_type": "H",
			"organization_type_full": null,
			"treasurer_name": "FARMER, GARY S.",
			"party_full": "REPUBLICAN PARTY",
			"city": "AUSTIN",
			"cycle": 2018,
			"state": "TX",
			"state_full": "Texas"
		},
		"fec_election_year": "2018",
		"contributor_city": "AUSTIN",
		"entity_type_desc": "INDIVIDUAL",
		"candidate_suffix": null,
		"image_number": "201812069134816143",
		"conduit_committee_city": null,
		"candidate_last_name": null,
		"transaction_id": "SA11AI.11156",
		"candidate_name": null,
		"receipt_type_full": null,
		"candidate_office_district": null,
		"contributor_street_2": null,
		"candidate_prefix": null,
		"contributor_street_1": "2546 SCENIC DR",
		"candidate_office_full": null,
		"is_individual": true,
		"report_year": 2018,
		"increased_limit": null,
		"contributor_suffix": null,
		"candidate_office_state": null,
		"contribution_receipt_amount": 250.0,
		"sub_id": "4121920181622525062",
		"receipt_type_desc": "CONTRIBUTION",
		"contributor_first_name": "JOHN",
		"unused_contbr_id": null,
		"back_reference_transaction_id": null,
		"contributor_state": "TX",
		"entity_type": "IND",
		"contribution_receipt_date": "2018-11-06T00:00:00",
		"conduit_committee_street1": null,
		"national_committee_nonfederal_account": null,
		"candidate_id": null,
		"candidate_first_name": null,
		"conduit_committee_name": null,
		"election_type_full": null,
		"contributor_employer": "SACHEM",
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"report_type": "30G",
		"schedule_type": "SA",
		"amendment_indicator_desc": "ADD",
		"line_number": "11AI",
		"load_date": "2018-12-20T02:51:49.663000+00:00",
		"donor_committee_name": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816143",
		"contributor_name": "MOONEY, JOHN MR."
	}, {
		"contributor_occupation": "INSURANCE",
		"contributor_aggregate_ytd": 5400.0,
		"memo_code": "X",
		"candidate_office": null,
		"contributor_last_name": "BOENKER",
		"file_number": 1298625,
		"recipient_committee_type": "H",
		"amendment_indicator": "A",
		"conduit_committee_street2": null,
		"memo_code_full": null,
		"committee_id": "C00498121",
		"contributor_middle_name": "HENRY",
		"two_year_transaction_period": 2018,
		"contributor_zip": "76135",
		"committee_name": null,
		"conduit_committee_state": null,
		"link_id": 4120620181620450055,
		"memoed_subtotal": true,
		"contributor_prefix": "MR.",
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"receipt_type": "15J",
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"candidate_middle_name": null,
		"fec_election_type_desc": "GENERAL",
		"line_number_label": "Transfers from authorized committees",
		"original_sub_id": null,
		"contributor": null,
		"memo_text": null,
		"back_reference_schedule_name": "SA12",
		"conduit_committee_id": null,
		"contributor_id": null,
		"committee": {
			"organization_type": null,
			"street_1": "P.O. BOX 91061",
			"committee_type_full": "House",
			"candidate_ids": ["H2TX33040"],
			"filing_frequency": "Q",
			"designation_full": "Principal campaign committee",
			"street_2": null,
			"cycles": [2012, 2014, 2016, 2018, 2020],
			"party": "REP",
			"committee_id": "C00498121",
			"zip": "787091061",
			"designation": "P",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_type": "H",
			"organization_type_full": null,
			"treasurer_name": "FARMER, GARY S.",
			"party_full": "REPUBLICAN PARTY",
			"city": "AUSTIN",
			"cycle": 2018,
			"state": "TX",
			"state_full": "Texas"
		},
		"fec_election_year": "2018",
		"contributor_city": "FORT WORTH",
		"entity_type_desc": "INDIVIDUAL",
		"candidate_suffix": null,
		"image_number": "201812069134816169",
		"conduit_committee_city": null,
		"candidate_last_name": null,
		"transaction_id": "SA12.11187.84",
		"candidate_name": null,
		"receipt_type_full": "JOINT FUNDRAISER - ROGER FOR CONGRESS VICTORY FUND",
		"candidate_office_district": null,
		"contributor_street_2": null,
		"candidate_prefix": null,
		"contributor_street_1": "6030 LAKE WORTH BLVD",
		"candidate_office_full": null,
		"is_individual": true,
		"report_year": 2018,
		"increased_limit": null,
		"contributor_suffix": "III",
		"candidate_office_state": null,
		"contribution_receipt_amount": 2700.0,
		"sub_id": "4121920181622525137",
		"receipt_type_desc": "MEMO (FILER'S % OF CONTRIBUTION GIVEN TO JOIN",
		"contributor_first_name": "ALVIN",
		"unused_contbr_id": null,
		"back_reference_transaction_id": "SA12.11187",
		"contributor_state": "TX",
		"entity_type": "IND",
		"contribution_receipt_date": "2018-11-05T00:00:00",
		"conduit_committee_street1": null,
		"national_committee_nonfederal_account": null,
		"candidate_id": null,
		"candidate_first_name": null,
		"conduit_committee_name": null,
		"election_type_full": null,
		"contributor_employer": "BOENKER GROUP OF COMPANIES",
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"report_type": "30G",
		"schedule_type": "SA",
		"amendment_indicator_desc": "ADD",
		"line_number": "12",
		"load_date": "2018-12-20T02:51:49.668000+00:00",
		"donor_committee_name": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816169",
		"contributor_name": "BOENKER, ALVIN HENRY MR. III"
	}, {
		"contributor_occupation": "BOOKKEEPER",
		"contributor_aggregate_ytd": 220.0,
		"memo_code": null,
		"candidate_office": null,
		"contributor_last_name": "WALLACE",
		"file_number": 1298625,
		"recipient_committee_type": "H",
		"amendment_indicator": "A",
		"conduit_committee_street2": null,
		"memo_code_full": null,
		"committee_id": "C00498121",
		"contributor_middle_name": "S.",
		"two_year_transaction_period": 2018,
		"contributor_zip": "92507",
		"committee_name": null,
		"conduit_committee_state": null,
		"link_id": 4120620181620450055,
		"memoed_subtotal": false,
		"contributor_prefix": "MS.",
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"receipt_type": "15",
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"candidate_middle_name": null,
		"fec_election_type_desc": "GENERAL",
		"line_number_label": "Contributions From Individuals\/Persons Other Than Political Committees",
		"original_sub_id": null,
		"contributor": null,
		"memo_text": null,
		"back_reference_schedule_name": null,
		"conduit_committee_id": null,
		"contributor_id": null,
		"committee": {
			"organization_type": null,
			"street_1": "P.O. BOX 91061",
			"committee_type_full": "House",
			"candidate_ids": ["H2TX33040"],
			"filing_frequency": "Q",
			"designation_full": "Principal campaign committee",
			"street_2": null,
			"cycles": [2012, 2014, 2016, 2018, 2020],
			"party": "REP",
			"committee_id": "C00498121",
			"zip": "787091061",
			"designation": "P",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_type": "H",
			"organization_type_full": null,
			"treasurer_name": "FARMER, GARY S.",
			"party_full": "REPUBLICAN PARTY",
			"city": "AUSTIN",
			"cycle": 2018,
			"state": "TX",
			"state_full": "Texas"
		},
		"fec_election_year": "2018",
		"contributor_city": "RIVERSIDE",
		"entity_type_desc": "INDIVIDUAL",
		"candidate_suffix": null,
		"image_number": "201812069134816143",
		"conduit_committee_city": null,
		"candidate_last_name": null,
		"transaction_id": "SA11AI.11162",
		"candidate_name": null,
		"receipt_type_full": null,
		"candidate_office_district": null,
		"contributor_street_2": null,
		"candidate_prefix": null,
		"contributor_street_1": "2710 10TH ST",
		"candidate_office_full": null,
		"is_individual": true,
		"report_year": 2018,
		"increased_limit": null,
		"contributor_suffix": null,
		"candidate_office_state": null,
		"contribution_receipt_amount": 10.0,
		"sub_id": "4121920181622525064",
		"receipt_type_desc": "CONTRIBUTION",
		"contributor_first_name": "DANELLE",
		"unused_contbr_id": null,
		"back_reference_transaction_id": null,
		"contributor_state": "CA",
		"entity_type": "IND",
		"contribution_receipt_date": "2018-11-05T00:00:00",
		"conduit_committee_street1": null,
		"national_committee_nonfederal_account": null,
		"candidate_id": null,
		"candidate_first_name": null,
		"conduit_committee_name": null,
		"election_type_full": null,
		"contributor_employer": "SELF EMPLOYED",
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"report_type": "30G",
		"schedule_type": "SA",
		"amendment_indicator_desc": "ADD",
		"line_number": "11AI",
		"load_date": "2018-12-20T02:51:49.663000+00:00",
		"donor_committee_name": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816143",
		"contributor_name": "WALLACE, DANELLE S. MS."
	}, {
		"contributor_occupation": "PARTNER\/CEO",
		"contributor_aggregate_ytd": 500.0,
		"memo_code": null,
		"candidate_office": null,
		"contributor_last_name": "BAILEY",
		"file_number": 1298625,
		"recipient_committee_type": "H",
		"amendment_indicator": "A",
		"conduit_committee_street2": null,
		"memo_code_full": null,
		"committee_id": "C00498121",
		"contributor_middle_name": "W.",
		"two_year_transaction_period": 2018,
		"contributor_zip": "75225",
		"committee_name": null,
		"conduit_committee_state": null,
		"link_id": 4120620181620450055,
		"memoed_subtotal": false,
		"contributor_prefix": "MR.",
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"receipt_type": "15",
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"candidate_middle_name": null,
		"fec_election_type_desc": "GENERAL",
		"line_number_label": "Contributions From Individuals\/Persons Other Than Political Committees",
		"original_sub_id": null,
		"contributor": null,
		"memo_text": null,
		"back_reference_schedule_name": null,
		"conduit_committee_id": null,
		"contributor_id": null,
		"committee": {
			"organization_type": null,
			"street_1": "P.O. BOX 91061",
			"committee_type_full": "House",
			"candidate_ids": ["H2TX33040"],
			"filing_frequency": "Q",
			"designation_full": "Principal campaign committee",
			"street_2": null,
			"cycles": [2012, 2014, 2016, 2018, 2020],
			"party": "REP",
			"committee_id": "C00498121",
			"zip": "787091061",
			"designation": "P",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_type": "H",
			"organization_type_full": null,
			"treasurer_name": "FARMER, GARY S.",
			"party_full": "REPUBLICAN PARTY",
			"city": "AUSTIN",
			"cycle": 2018,
			"state": "TX",
			"state_full": "Texas"
		},
		"fec_election_year": "2018",
		"contributor_city": "DALLAS",
		"entity_type_desc": "INDIVIDUAL",
		"candidate_suffix": null,
		"image_number": "201812069134816137",
		"conduit_committee_city": null,
		"candidate_last_name": null,
		"transaction_id": "SA11AI.11143",
		"candidate_name": null,
		"receipt_type_full": null,
		"candidate_office_district": null,
		"contributor_street_2": null,
		"candidate_prefix": null,
		"contributor_street_1": "3312 MARQUETTE ST",
		"candidate_office_full": null,
		"is_individual": true,
		"report_year": 2018,
		"increased_limit": null,
		"contributor_suffix": null,
		"candidate_office_state": null,
		"contribution_receipt_amount": 500.0,
		"sub_id": "4121920181622525046",
		"receipt_type_desc": "CONTRIBUTION",
		"contributor_first_name": "ROY",
		"unused_contbr_id": null,
		"back_reference_transaction_id": null,
		"contributor_state": "TX",
		"entity_type": "IND",
		"contribution_receipt_date": "2018-11-05T00:00:00",
		"conduit_committee_street1": null,
		"national_committee_nonfederal_account": null,
		"candidate_id": null,
		"candidate_first_name": null,
		"conduit_committee_name": null,
		"election_type_full": null,
		"contributor_employer": "BAILEY DEASON CAPITAL INTERESTS LLC",
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"report_type": "30G",
		"schedule_type": "SA",
		"amendment_indicator_desc": "ADD",
		"line_number": "11AI",
		"load_date": "2018-12-20T02:51:49.663000+00:00",
		"donor_committee_name": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816137",
		"contributor_name": "BAILEY, ROY W. MR."
	}, {
		"contributor_occupation": "GOVERNMENT AFFAIRS",
		"contributor_aggregate_ytd": 300.0,
		"memo_code": "X",
		"candidate_office": null,
		"contributor_last_name": "MICA",
		"file_number": 1298625,
		"recipient_committee_type": "H",
		"amendment_indicator": "A",
		"conduit_committee_street2": null,
		"memo_code_full": null,
		"committee_id": "C00498121",
		"contributor_middle_name": "B.",
		"two_year_transaction_period": 2018,
		"contributor_zip": "78732",
		"committee_name": null,
		"conduit_committee_state": null,
		"link_id": 4120620181620450055,
		"memoed_subtotal": true,
		"contributor_prefix": "MR.",
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"receipt_type": "15J",
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"candidate_middle_name": null,
		"fec_election_type_desc": "GENERAL",
		"line_number_label": "Transfers from authorized committees",
		"original_sub_id": null,
		"contributor": null,
		"memo_text": null,
		"back_reference_schedule_name": "SA12",
		"conduit_committee_id": null,
		"contributor_id": null,
		"committee": {
			"organization_type": null,
			"street_1": "P.O. BOX 91061",
			"committee_type_full": "House",
			"candidate_ids": ["H2TX33040"],
			"filing_frequency": "Q",
			"designation_full": "Principal campaign committee",
			"street_2": null,
			"cycles": [2012, 2014, 2016, 2018, 2020],
			"party": "REP",
			"committee_id": "C00498121",
			"zip": "787091061",
			"designation": "P",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_type": "H",
			"organization_type_full": null,
			"treasurer_name": "FARMER, GARY S.",
			"party_full": "REPUBLICAN PARTY",
			"city": "AUSTIN",
			"cycle": 2018,
			"state": "TX",
			"state_full": "Texas"
		},
		"fec_election_year": "2018",
		"contributor_city": "AUSTIN",
		"entity_type_desc": "INDIVIDUAL",
		"candidate_suffix": null,
		"image_number": "201812069134816168",
		"conduit_committee_city": null,
		"candidate_last_name": null,
		"transaction_id": "SA12.11187.83",
		"candidate_name": null,
		"receipt_type_full": "JOINT FUNDRAISER - ROGER FOR CONGRESS VICTORY FUND",
		"candidate_office_district": null,
		"contributor_street_2": null,
		"candidate_prefix": null,
		"contributor_street_1": "12405 VON HERFF CT",
		"candidate_office_full": null,
		"is_individual": true,
		"report_year": 2018,
		"increased_limit": null,
		"contributor_suffix": null,
		"candidate_office_state": null,
		"contribution_receipt_amount": 300.0,
		"sub_id": "4121920181622525136",
		"receipt_type_desc": "MEMO (FILER'S % OF CONTRIBUTION GIVEN TO JOIN",
		"contributor_first_name": "CARL",
		"unused_contbr_id": null,
		"back_reference_transaction_id": "SA12.11187",
		"contributor_state": "TX",
		"entity_type": "IND",
		"contribution_receipt_date": "2018-11-03T00:00:00",
		"conduit_committee_street1": null,
		"national_committee_nonfederal_account": null,
		"candidate_id": null,
		"candidate_first_name": null,
		"conduit_committee_name": null,
		"election_type_full": null,
		"contributor_employer": "UNIVERSITY OF TEXAS SYSTEMS",
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"report_type": "30G",
		"schedule_type": "SA",
		"amendment_indicator_desc": "ADD",
		"line_number": "12",
		"load_date": "2018-12-20T02:51:49.668000+00:00",
		"donor_committee_name": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816168",
		"contributor_name": "MICA, CARL B. MR."
	}, {
		"contributor_occupation": "FINANCE",
		"contributor_aggregate_ytd": 1000.0,
		"memo_code": null,
		"candidate_office": null,
		"contributor_last_name": "KEITH",
		"file_number": 1298625,
		"recipient_committee_type": "H",
		"amendment_indicator": "A",
		"conduit_committee_street2": null,
		"memo_code_full": null,
		"committee_id": "C00498121",
		"contributor_middle_name": "A.",
		"two_year_transaction_period": 2018,
		"contributor_zip": "028404105",
		"committee_name": null,
		"conduit_committee_state": null,
		"link_id": 4120620181620450055,
		"memoed_subtotal": false,
		"contributor_prefix": "MR.",
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"receipt_type": "15",
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"candidate_middle_name": null,
		"fec_election_type_desc": "GENERAL",
		"line_number_label": "Contributions From Individuals\/Persons Other Than Political Committees",
		"original_sub_id": null,
		"contributor": null,
		"memo_text": null,
		"back_reference_schedule_name": null,
		"conduit_committee_id": null,
		"contributor_id": null,
		"committee": {
			"organization_type": null,
			"street_1": "P.O. BOX 91061",
			"committee_type_full": "House",
			"candidate_ids": ["H2TX33040"],
			"filing_frequency": "Q",
			"designation_full": "Principal campaign committee",
			"street_2": null,
			"cycles": [2012, 2014, 2016, 2018, 2020],
			"party": "REP",
			"committee_id": "C00498121",
			"zip": "787091061",
			"designation": "P",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_type": "H",
			"organization_type_full": null,
			"treasurer_name": "FARMER, GARY S.",
			"party_full": "REPUBLICAN PARTY",
			"city": "AUSTIN",
			"cycle": 2018,
			"state": "TX",
			"state_full": "Texas"
		},
		"fec_election_year": "2018",
		"contributor_city": "NEWPORT",
		"entity_type_desc": "INDIVIDUAL",
		"candidate_suffix": null,
		"image_number": "201812069134816141",
		"conduit_committee_city": null,
		"candidate_last_name": null,
		"transaction_id": "SA11AI.10879",
		"candidate_name": null,
		"receipt_type_full": null,
		"candidate_office_district": null,
		"contributor_street_2": null,
		"candidate_prefix": null,
		"contributor_street_1": "17 LEROY AVE.",
		"candidate_office_full": null,
		"is_individual": true,
		"report_year": 2018,
		"increased_limit": null,
		"contributor_suffix": null,
		"candidate_office_state": null,
		"contribution_receipt_amount": 1000.0,
		"sub_id": "4121920181622525056",
		"receipt_type_desc": "CONTRIBUTION",
		"contributor_first_name": "PATRICK",
		"unused_contbr_id": null,
		"back_reference_transaction_id": null,
		"contributor_state": "RI",
		"entity_type": "IND",
		"contribution_receipt_date": "2018-11-02T00:00:00",
		"conduit_committee_street1": null,
		"national_committee_nonfederal_account": null,
		"candidate_id": null,
		"candidate_first_name": null,
		"conduit_committee_name": null,
		"election_type_full": null,
		"contributor_employer": "SELF EMPLOYED",
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"report_type": "30G",
		"schedule_type": "SA",
		"amendment_indicator_desc": "ADD",
		"line_number": "11AI",
		"load_date": "2018-12-20T02:51:49.663000+00:00",
		"donor_committee_name": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816141",
		"contributor_name": "KEITH, PATRICK A. MR."
	}],
	"pagination": {
		"count": 971,
		"per_page": 10,
		"pages": 98,
		"last_indexes": {
			"last_index": "4121920181622525056",
			"last_contribution_receipt_date": "2018-11-02T00:00:00"
		}
	}
}
MacBook - Pro - 6: FEC - NodeScraper matthewoliver$ curl 'https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=false&sort_nulls_last=true&sort=-contribution_receipt_date&per_page=10&committee_id=C00498121&two_year_transaction_period=2018&is_individual=true' - H 'Origin: https://www.fec.gov' - H 'Accept-Encoding: gzip, deflate, br' - H 'Accept-Language: en-US,en;q=0.9' - H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' - H 'Accept: application/json, text/javascript, */*; q=0.01' - H 'Referer: https://www.fec.gov/data/committee/C00498121/?cycle=2018&tab=raising' - H 'Connection: keep-alive'--compressed {
	"api_version": "1.0",
	"results": [{
		"contributor_employer": "CLEAR CHANNEL COMMUNICATIONS, INC.",
		"contributor_last_name": "MAYS",
		"contributor_name": "MAYS, L. LOWRY MR.",
		"candidate_office_district": null,
		"election_type_full": null,
		"contributor_aggregate_ytd": 500.0,
		"unused_contbr_id": null,
		"entity_type": "IND",
		"committee": {
			"candidate_ids": ["H2TX33040"],
			"organization_type": null,
			"city": "AUSTIN",
			"zip": "787091061",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_id": "C00498121",
			"filing_frequency": "Q",
			"organization_type_full": null,
			"designation": "P",
			"street_2": null,
			"state_full": "Texas",
			"street_1": "P.O. BOX 91061",
			"state": "TX",
			"party_full": "REPUBLICAN PARTY",
			"committee_type_full": "House",
			"party": "REP",
			"committee_type": "H",
			"designation_full": "Principal campaign committee",
			"treasurer_name": "FARMER, GARY S.",
			"cycle": 2018,
			"cycles": [2012, 2014, 2016, 2018, 2020]
		},
		"line_number": "11AI",
		"fec_election_type_desc": "GENERAL",
		"candidate_name": null,
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"file_number": 1298625,
		"amendment_indicator_desc": "ADD",
		"contributor_suffix": null,
		"contributor_state": "TX",
		"candidate_office": null,
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"conduit_committee_state": null,
		"contributor_street_2": null,
		"contributor_occupation": "CHAIRMAN & CEO - RETIRED",
		"conduit_committee_street1": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816142",
		"amendment_indicator": "A",
		"contributor": null,
		"contribution_receipt_date": "2018-11-09T00:00:00",
		"committee_id": "C00498121",
		"contributor_street_1": "250 W NOTTINGHAM DR STE 400",
		"schedule_type": "SA",
		"transaction_id": "SA11AI.11152",
		"candidate_last_name": null,
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"report_type": "30G",
		"memo_code_full": null,
		"line_number_label": "Contributions From Individuals\/Persons Other Than Political Committees",
		"memo_code": null,
		"donor_committee_name": null,
		"receipt_type": "15",
		"candidate_middle_name": null,
		"load_date": "2018-12-20T02:51:49.663000+00:00",
		"contribution_receipt_amount": 500.0,
		"fec_election_year": "2018",
		"contributor_id": null,
		"candidate_office_full": null,
		"image_number": "201812069134816142",
		"conduit_committee_id": null,
		"candidate_suffix": null,
		"contributor_prefix": "MR.",
		"conduit_committee_city": null,
		"contributor_zip": "78209",
		"memo_text": null,
		"report_year": 2018,
		"sub_id": "4121920181622525060",
		"contributor_first_name": "L.",
		"original_sub_id": null,
		"contributor_middle_name": "LOWRY",
		"back_reference_transaction_id": null,
		"entity_type_desc": "INDIVIDUAL",
		"national_committee_nonfederal_account": null,
		"candidate_prefix": null,
		"increased_limit": null,
		"contributor_city": "SAN ANTONIO",
		"receipt_type_desc": "CONTRIBUTION",
		"back_reference_schedule_name": null,
		"recipient_committee_type": "H",
		"receipt_type_full": "POSTMARKED AND DATED BEFORE 11\/06\/18",
		"is_individual": true,
		"link_id": 4120620181620450055,
		"candidate_first_name": null,
		"conduit_committee_street2": null,
		"committee_name": null,
		"memoed_subtotal": false,
		"candidate_id": null,
		"two_year_transaction_period": 2018,
		"candidate_office_state": null,
		"conduit_committee_name": null
	}, {
		"contributor_employer": "FOUR SEVENS OIL CO.",
		"contributor_last_name": "CUNNINGHAM",
		"contributor_name": "CUNNINGHAM, BRAD MR.",
		"candidate_office_district": null,
		"election_type_full": null,
		"contributor_aggregate_ytd": 2700.0,
		"unused_contbr_id": null,
		"entity_type": "IND",
		"committee": {
			"candidate_ids": ["H2TX33040"],
			"organization_type": null,
			"city": "AUSTIN",
			"zip": "787091061",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_id": "C00498121",
			"filing_frequency": "Q",
			"organization_type_full": null,
			"designation": "P",
			"street_2": null,
			"state_full": "Texas",
			"street_1": "P.O. BOX 91061",
			"state": "TX",
			"party_full": "REPUBLICAN PARTY",
			"committee_type_full": "House",
			"party": "REP",
			"committee_type": "H",
			"designation_full": "Principal campaign committee",
			"treasurer_name": "FARMER, GARY S.",
			"cycle": 2018,
			"cycles": [2012, 2014, 2016, 2018, 2020]
		},
		"line_number": "12",
		"fec_election_type_desc": "GENERAL",
		"candidate_name": null,
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"file_number": 1298625,
		"amendment_indicator_desc": "ADD",
		"contributor_suffix": null,
		"contributor_state": "TX",
		"candidate_office": null,
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"conduit_committee_state": null,
		"contributor_street_2": null,
		"contributor_occupation": "OIL & GAS",
		"conduit_committee_street1": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816169",
		"amendment_indicator": "A",
		"contributor": null,
		"contribution_receipt_date": "2018-11-06T00:00:00",
		"committee_id": "C00498121",
		"contributor_street_1": "4901 E BANKHEAD HWY",
		"schedule_type": "SA",
		"transaction_id": "SA12.11187.86",
		"candidate_last_name": null,
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"report_type": "30G",
		"memo_code_full": null,
		"line_number_label": "Transfers from authorized committees",
		"memo_code": "X",
		"donor_committee_name": null,
		"receipt_type": "15J",
		"candidate_middle_name": null,
		"load_date": "2018-12-20T02:51:49.668000+00:00",
		"contribution_receipt_amount": 2700.0,
		"fec_election_year": "2018",
		"contributor_id": null,
		"candidate_office_full": null,
		"image_number": "201812069134816169",
		"conduit_committee_id": null,
		"candidate_suffix": null,
		"contributor_prefix": "MR.",
		"conduit_committee_city": null,
		"contributor_zip": "76087",
		"memo_text": null,
		"report_year": 2018,
		"sub_id": "4121920181622525139",
		"contributor_first_name": "BRAD",
		"original_sub_id": null,
		"contributor_middle_name": null,
		"back_reference_transaction_id": "SA12.11187",
		"entity_type_desc": "INDIVIDUAL",
		"national_committee_nonfederal_account": null,
		"candidate_prefix": null,
		"increased_limit": null,
		"contributor_city": "HUDSON OAKS",
		"receipt_type_desc": "MEMO (FILER'S % OF CONTRIBUTION GIVEN TO JOIN",
		"back_reference_schedule_name": "SA12",
		"recipient_committee_type": "H",
		"receipt_type_full": "JOINT FUNDRAISER - ROGER FOR CONGRESS VICTORY FUND",
		"is_individual": true,
		"link_id": 4120620181620450055,
		"candidate_first_name": null,
		"conduit_committee_street2": null,
		"committee_name": null,
		"memoed_subtotal": true,
		"candidate_id": null,
		"two_year_transaction_period": 2018,
		"candidate_office_state": null,
		"conduit_committee_name": null
	}, {
		"contributor_employer": "FOUR SEVENS OIL",
		"contributor_last_name": "LOWE",
		"contributor_name": "LOWE, DICK MR.",
		"candidate_office_district": null,
		"election_type_full": null,
		"contributor_aggregate_ytd": 2700.0,
		"unused_contbr_id": null,
		"entity_type": "IND",
		"committee": {
			"candidate_ids": ["H2TX33040"],
			"organization_type": null,
			"city": "AUSTIN",
			"zip": "787091061",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_id": "C00498121",
			"filing_frequency": "Q",
			"organization_type_full": null,
			"designation": "P",
			"street_2": null,
			"state_full": "Texas",
			"street_1": "P.O. BOX 91061",
			"state": "TX",
			"party_full": "REPUBLICAN PARTY",
			"committee_type_full": "House",
			"party": "REP",
			"committee_type": "H",
			"designation_full": "Principal campaign committee",
			"treasurer_name": "FARMER, GARY S.",
			"cycle": 2018,
			"cycles": [2012, 2014, 2016, 2018, 2020]
		},
		"line_number": "12",
		"fec_election_type_desc": "GENERAL",
		"candidate_name": null,
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"file_number": 1298625,
		"amendment_indicator_desc": "ADD",
		"contributor_suffix": null,
		"contributor_state": "TX",
		"candidate_office": null,
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"conduit_committee_state": null,
		"contributor_street_2": null,
		"contributor_occupation": "PARTNER",
		"conduit_committee_street1": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816169",
		"amendment_indicator": "A",
		"contributor": null,
		"contribution_receipt_date": "2018-11-06T00:00:00",
		"committee_id": "C00498121",
		"contributor_street_1": "701 CINNABAR CT",
		"schedule_type": "SA",
		"transaction_id": "SA12.11187.85",
		"candidate_last_name": null,
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"report_type": "30G",
		"memo_code_full": null,
		"line_number_label": "Transfers from authorized committees",
		"memo_code": "X",
		"donor_committee_name": null,
		"receipt_type": "15J",
		"candidate_middle_name": null,
		"load_date": "2018-12-20T02:51:49.668000+00:00",
		"contribution_receipt_amount": 2700.0,
		"fec_election_year": "2018",
		"contributor_id": null,
		"candidate_office_full": null,
		"image_number": "201812069134816169",
		"conduit_committee_id": null,
		"candidate_suffix": null,
		"contributor_prefix": "MR.",
		"conduit_committee_city": null,
		"contributor_zip": "76114",
		"memo_text": null,
		"report_year": 2018,
		"sub_id": "4121920181622525138",
		"contributor_first_name": "DICK",
		"original_sub_id": null,
		"contributor_middle_name": null,
		"back_reference_transaction_id": "SA12.11187",
		"entity_type_desc": "INDIVIDUAL",
		"national_committee_nonfederal_account": null,
		"candidate_prefix": null,
		"increased_limit": null,
		"contributor_city": "WESTWORTH VILLAGE",
		"receipt_type_desc": "MEMO (FILER'S % OF CONTRIBUTION GIVEN TO JOIN",
		"back_reference_schedule_name": "SA12",
		"recipient_committee_type": "H",
		"receipt_type_full": "JOINT FUNDRAISER - ROGER FOR CONGRESS VICTORY FUND",
		"is_individual": true,
		"link_id": 4120620181620450055,
		"candidate_first_name": null,
		"conduit_committee_street2": null,
		"committee_name": null,
		"memoed_subtotal": true,
		"candidate_id": null,
		"two_year_transaction_period": 2018,
		"candidate_office_state": null,
		"conduit_committee_name": null
	}, {
		"contributor_employer": "RETIRED",
		"contributor_last_name": "MOONEY",
		"contributor_name": "MOONEY, KATHERINE MRS.",
		"candidate_office_district": null,
		"election_type_full": null,
		"contributor_aggregate_ytd": 750.0,
		"unused_contbr_id": null,
		"entity_type": "IND",
		"committee": {
			"candidate_ids": ["H2TX33040"],
			"organization_type": null,
			"city": "AUSTIN",
			"zip": "787091061",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_id": "C00498121",
			"filing_frequency": "Q",
			"organization_type_full": null,
			"designation": "P",
			"street_2": null,
			"state_full": "Texas",
			"street_1": "P.O. BOX 91061",
			"state": "TX",
			"party_full": "REPUBLICAN PARTY",
			"committee_type_full": "House",
			"party": "REP",
			"committee_type": "H",
			"designation_full": "Principal campaign committee",
			"treasurer_name": "FARMER, GARY S.",
			"cycle": 2018,
			"cycles": [2012, 2014, 2016, 2018, 2020]
		},
		"line_number": "11AI",
		"fec_election_type_desc": "GENERAL",
		"candidate_name": null,
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"file_number": 1298625,
		"amendment_indicator_desc": "ADD",
		"contributor_suffix": null,
		"contributor_state": "TX",
		"candidate_office": null,
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"conduit_committee_state": null,
		"contributor_street_2": null,
		"contributor_occupation": "RETIRED",
		"conduit_committee_street1": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816143",
		"amendment_indicator": "A",
		"contributor": null,
		"contribution_receipt_date": "2018-11-06T00:00:00",
		"committee_id": "C00498121",
		"contributor_street_1": "2546 SCENIC DR",
		"schedule_type": "SA",
		"transaction_id": "SA11AI.11158",
		"candidate_last_name": null,
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"report_type": "30G",
		"memo_code_full": null,
		"line_number_label": "Contributions From Individuals\/Persons Other Than Political Committees",
		"memo_code": null,
		"donor_committee_name": null,
		"receipt_type": "15",
		"candidate_middle_name": null,
		"load_date": "2018-12-20T02:51:49.663000+00:00",
		"contribution_receipt_amount": 750.0,
		"fec_election_year": "2018",
		"contributor_id": null,
		"candidate_office_full": null,
		"image_number": "201812069134816143",
		"conduit_committee_id": null,
		"candidate_suffix": null,
		"contributor_prefix": "MRS.",
		"conduit_committee_city": null,
		"contributor_zip": "78703",
		"memo_text": null,
		"report_year": 2018,
		"sub_id": "4121920181622525063",
		"contributor_first_name": "KATHERINE",
		"original_sub_id": null,
		"contributor_middle_name": null,
		"back_reference_transaction_id": null,
		"entity_type_desc": "INDIVIDUAL",
		"national_committee_nonfederal_account": null,
		"candidate_prefix": null,
		"increased_limit": null,
		"contributor_city": "AUSTIN",
		"receipt_type_desc": "CONTRIBUTION",
		"back_reference_schedule_name": null,
		"recipient_committee_type": "H",
		"receipt_type_full": null,
		"is_individual": true,
		"link_id": 4120620181620450055,
		"candidate_first_name": null,
		"conduit_committee_street2": null,
		"committee_name": null,
		"memoed_subtotal": false,
		"candidate_id": null,
		"two_year_transaction_period": 2018,
		"candidate_office_state": null,
		"conduit_committee_name": null
	}, {
		"contributor_employer": "SACHEM",
		"contributor_last_name": "MOONEY",
		"contributor_name": "MOONEY, JOHN MR.",
		"candidate_office_district": null,
		"election_type_full": null,
		"contributor_aggregate_ytd": 250.0,
		"unused_contbr_id": null,
		"entity_type": "IND",
		"committee": {
			"candidate_ids": ["H2TX33040"],
			"organization_type": null,
			"city": "AUSTIN",
			"zip": "787091061",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_id": "C00498121",
			"filing_frequency": "Q",
			"organization_type_full": null,
			"designation": "P",
			"street_2": null,
			"state_full": "Texas",
			"street_1": "P.O. BOX 91061",
			"state": "TX",
			"party_full": "REPUBLICAN PARTY",
			"committee_type_full": "House",
			"party": "REP",
			"committee_type": "H",
			"designation_full": "Principal campaign committee",
			"treasurer_name": "FARMER, GARY S.",
			"cycle": 2018,
			"cycles": [2012, 2014, 2016, 2018, 2020]
		},
		"line_number": "11AI",
		"fec_election_type_desc": "GENERAL",
		"candidate_name": null,
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"file_number": 1298625,
		"amendment_indicator_desc": "ADD",
		"contributor_suffix": null,
		"contributor_state": "TX",
		"candidate_office": null,
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"conduit_committee_state": null,
		"contributor_street_2": null,
		"contributor_occupation": "MANAGER",
		"conduit_committee_street1": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816143",
		"amendment_indicator": "A",
		"contributor": null,
		"contribution_receipt_date": "2018-11-06T00:00:00",
		"committee_id": "C00498121",
		"contributor_street_1": "2546 SCENIC DR",
		"schedule_type": "SA",
		"transaction_id": "SA11AI.11156",
		"candidate_last_name": null,
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"report_type": "30G",
		"memo_code_full": null,
		"line_number_label": "Contributions From Individuals\/Persons Other Than Political Committees",
		"memo_code": null,
		"donor_committee_name": null,
		"receipt_type": "15",
		"candidate_middle_name": null,
		"load_date": "2018-12-20T02:51:49.663000+00:00",
		"contribution_receipt_amount": 250.0,
		"fec_election_year": "2018",
		"contributor_id": null,
		"candidate_office_full": null,
		"image_number": "201812069134816143",
		"conduit_committee_id": null,
		"candidate_suffix": null,
		"contributor_prefix": "MR.",
		"conduit_committee_city": null,
		"contributor_zip": "78703",
		"memo_text": null,
		"report_year": 2018,
		"sub_id": "4121920181622525062",
		"contributor_first_name": "JOHN",
		"original_sub_id": null,
		"contributor_middle_name": null,
		"back_reference_transaction_id": null,
		"entity_type_desc": "INDIVIDUAL",
		"national_committee_nonfederal_account": null,
		"candidate_prefix": null,
		"increased_limit": null,
		"contributor_city": "AUSTIN",
		"receipt_type_desc": "CONTRIBUTION",
		"back_reference_schedule_name": null,
		"recipient_committee_type": "H",
		"receipt_type_full": null,
		"is_individual": true,
		"link_id": 4120620181620450055,
		"candidate_first_name": null,
		"conduit_committee_street2": null,
		"committee_name": null,
		"memoed_subtotal": false,
		"candidate_id": null,
		"two_year_transaction_period": 2018,
		"candidate_office_state": null,
		"conduit_committee_name": null
	}, {
		"contributor_employer": "BOENKER GROUP OF COMPANIES",
		"contributor_last_name": "BOENKER",
		"contributor_name": "BOENKER, ALVIN HENRY MR. III",
		"candidate_office_district": null,
		"election_type_full": null,
		"contributor_aggregate_ytd": 5400.0,
		"unused_contbr_id": null,
		"entity_type": "IND",
		"committee": {
			"candidate_ids": ["H2TX33040"],
			"organization_type": null,
			"city": "AUSTIN",
			"zip": "787091061",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_id": "C00498121",
			"filing_frequency": "Q",
			"organization_type_full": null,
			"designation": "P",
			"street_2": null,
			"state_full": "Texas",
			"street_1": "P.O. BOX 91061",
			"state": "TX",
			"party_full": "REPUBLICAN PARTY",
			"committee_type_full": "House",
			"party": "REP",
			"committee_type": "H",
			"designation_full": "Principal campaign committee",
			"treasurer_name": "FARMER, GARY S.",
			"cycle": 2018,
			"cycles": [2012, 2014, 2016, 2018, 2020]
		},
		"line_number": "12",
		"fec_election_type_desc": "GENERAL",
		"candidate_name": null,
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"file_number": 1298625,
		"amendment_indicator_desc": "ADD",
		"contributor_suffix": "III",
		"contributor_state": "TX",
		"candidate_office": null,
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"conduit_committee_state": null,
		"contributor_street_2": null,
		"contributor_occupation": "INSURANCE",
		"conduit_committee_street1": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816169",
		"amendment_indicator": "A",
		"contributor": null,
		"contribution_receipt_date": "2018-11-05T00:00:00",
		"committee_id": "C00498121",
		"contributor_street_1": "6030 LAKE WORTH BLVD",
		"schedule_type": "SA",
		"transaction_id": "SA12.11187.84",
		"candidate_last_name": null,
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"report_type": "30G",
		"memo_code_full": null,
		"line_number_label": "Transfers from authorized committees",
		"memo_code": "X",
		"donor_committee_name": null,
		"receipt_type": "15J",
		"candidate_middle_name": null,
		"load_date": "2018-12-20T02:51:49.668000+00:00",
		"contribution_receipt_amount": 2700.0,
		"fec_election_year": "2018",
		"contributor_id": null,
		"candidate_office_full": null,
		"image_number": "201812069134816169",
		"conduit_committee_id": null,
		"candidate_suffix": null,
		"contributor_prefix": "MR.",
		"conduit_committee_city": null,
		"contributor_zip": "76135",
		"memo_text": null,
		"report_year": 2018,
		"sub_id": "4121920181622525137",
		"contributor_first_name": "ALVIN",
		"original_sub_id": null,
		"contributor_middle_name": "HENRY",
		"back_reference_transaction_id": "SA12.11187",
		"entity_type_desc": "INDIVIDUAL",
		"national_committee_nonfederal_account": null,
		"candidate_prefix": null,
		"increased_limit": null,
		"contributor_city": "FORT WORTH",
		"receipt_type_desc": "MEMO (FILER'S % OF CONTRIBUTION GIVEN TO JOIN",
		"back_reference_schedule_name": "SA12",
		"recipient_committee_type": "H",
		"receipt_type_full": "JOINT FUNDRAISER - ROGER FOR CONGRESS VICTORY FUND",
		"is_individual": true,
		"link_id": 4120620181620450055,
		"candidate_first_name": null,
		"conduit_committee_street2": null,
		"committee_name": null,
		"memoed_subtotal": true,
		"candidate_id": null,
		"two_year_transaction_period": 2018,
		"candidate_office_state": null,
		"conduit_committee_name": null
	}, {
		"contributor_employer": "SELF EMPLOYED",
		"contributor_last_name": "WALLACE",
		"contributor_name": "WALLACE, DANELLE S. MS.",
		"candidate_office_district": null,
		"election_type_full": null,
		"contributor_aggregate_ytd": 220.0,
		"unused_contbr_id": null,
		"entity_type": "IND",
		"committee": {
			"candidate_ids": ["H2TX33040"],
			"organization_type": null,
			"city": "AUSTIN",
			"zip": "787091061",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_id": "C00498121",
			"filing_frequency": "Q",
			"organization_type_full": null,
			"designation": "P",
			"street_2": null,
			"state_full": "Texas",
			"street_1": "P.O. BOX 91061",
			"state": "TX",
			"party_full": "REPUBLICAN PARTY",
			"committee_type_full": "House",
			"party": "REP",
			"committee_type": "H",
			"designation_full": "Principal campaign committee",
			"treasurer_name": "FARMER, GARY S.",
			"cycle": 2018,
			"cycles": [2012, 2014, 2016, 2018, 2020]
		},
		"line_number": "11AI",
		"fec_election_type_desc": "GENERAL",
		"candidate_name": null,
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"file_number": 1298625,
		"amendment_indicator_desc": "ADD",
		"contributor_suffix": null,
		"contributor_state": "CA",
		"candidate_office": null,
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"conduit_committee_state": null,
		"contributor_street_2": null,
		"contributor_occupation": "BOOKKEEPER",
		"conduit_committee_street1": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816143",
		"amendment_indicator": "A",
		"contributor": null,
		"contribution_receipt_date": "2018-11-05T00:00:00",
		"committee_id": "C00498121",
		"contributor_street_1": "2710 10TH ST",
		"schedule_type": "SA",
		"transaction_id": "SA11AI.11162",
		"candidate_last_name": null,
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"report_type": "30G",
		"memo_code_full": null,
		"line_number_label": "Contributions From Individuals\/Persons Other Than Political Committees",
		"memo_code": null,
		"donor_committee_name": null,
		"receipt_type": "15",
		"candidate_middle_name": null,
		"load_date": "2018-12-20T02:51:49.663000+00:00",
		"contribution_receipt_amount": 10.0,
		"fec_election_year": "2018",
		"contributor_id": null,
		"candidate_office_full": null,
		"image_number": "201812069134816143",
		"conduit_committee_id": null,
		"candidate_suffix": null,
		"contributor_prefix": "MS.",
		"conduit_committee_city": null,
		"contributor_zip": "92507",
		"memo_text": null,
		"report_year": 2018,
		"sub_id": "4121920181622525064",
		"contributor_first_name": "DANELLE",
		"original_sub_id": null,
		"contributor_middle_name": "S.",
		"back_reference_transaction_id": null,
		"entity_type_desc": "INDIVIDUAL",
		"national_committee_nonfederal_account": null,
		"candidate_prefix": null,
		"increased_limit": null,
		"contributor_city": "RIVERSIDE",
		"receipt_type_desc": "CONTRIBUTION",
		"back_reference_schedule_name": null,
		"recipient_committee_type": "H",
		"receipt_type_full": null,
		"is_individual": true,
		"link_id": 4120620181620450055,
		"candidate_first_name": null,
		"conduit_committee_street2": null,
		"committee_name": null,
		"memoed_subtotal": false,
		"candidate_id": null,
		"two_year_transaction_period": 2018,
		"candidate_office_state": null,
		"conduit_committee_name": null
	}, {
		"contributor_employer": "BAILEY DEASON CAPITAL INTERESTS LLC",
		"contributor_last_name": "BAILEY",
		"contributor_name": "BAILEY, ROY W. MR.",
		"candidate_office_district": null,
		"election_type_full": null,
		"contributor_aggregate_ytd": 500.0,
		"unused_contbr_id": null,
		"entity_type": "IND",
		"committee": {
			"candidate_ids": ["H2TX33040"],
			"organization_type": null,
			"city": "AUSTIN",
			"zip": "787091061",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_id": "C00498121",
			"filing_frequency": "Q",
			"organization_type_full": null,
			"designation": "P",
			"street_2": null,
			"state_full": "Texas",
			"street_1": "P.O. BOX 91061",
			"state": "TX",
			"party_full": "REPUBLICAN PARTY",
			"committee_type_full": "House",
			"party": "REP",
			"committee_type": "H",
			"designation_full": "Principal campaign committee",
			"treasurer_name": "FARMER, GARY S.",
			"cycle": 2018,
			"cycles": [2012, 2014, 2016, 2018, 2020]
		},
		"line_number": "11AI",
		"fec_election_type_desc": "GENERAL",
		"candidate_name": null,
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"file_number": 1298625,
		"amendment_indicator_desc": "ADD",
		"contributor_suffix": null,
		"contributor_state": "TX",
		"candidate_office": null,
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"conduit_committee_state": null,
		"contributor_street_2": null,
		"contributor_occupation": "PARTNER\/CEO",
		"conduit_committee_street1": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816137",
		"amendment_indicator": "A",
		"contributor": null,
		"contribution_receipt_date": "2018-11-05T00:00:00",
		"committee_id": "C00498121",
		"contributor_street_1": "3312 MARQUETTE ST",
		"schedule_type": "SA",
		"transaction_id": "SA11AI.11143",
		"candidate_last_name": null,
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"report_type": "30G",
		"memo_code_full": null,
		"line_number_label": "Contributions From Individuals\/Persons Other Than Political Committees",
		"memo_code": null,
		"donor_committee_name": null,
		"receipt_type": "15",
		"candidate_middle_name": null,
		"load_date": "2018-12-20T02:51:49.663000+00:00",
		"contribution_receipt_amount": 500.0,
		"fec_election_year": "2018",
		"contributor_id": null,
		"candidate_office_full": null,
		"image_number": "201812069134816137",
		"conduit_committee_id": null,
		"candidate_suffix": null,
		"contributor_prefix": "MR.",
		"conduit_committee_city": null,
		"contributor_zip": "75225",
		"memo_text": null,
		"report_year": 2018,
		"sub_id": "4121920181622525046",
		"contributor_first_name": "ROY",
		"original_sub_id": null,
		"contributor_middle_name": "W.",
		"back_reference_transaction_id": null,
		"entity_type_desc": "INDIVIDUAL",
		"national_committee_nonfederal_account": null,
		"candidate_prefix": null,
		"increased_limit": null,
		"contributor_city": "DALLAS",
		"receipt_type_desc": "CONTRIBUTION",
		"back_reference_schedule_name": null,
		"recipient_committee_type": "H",
		"receipt_type_full": null,
		"is_individual": true,
		"link_id": 4120620181620450055,
		"candidate_first_name": null,
		"conduit_committee_street2": null,
		"committee_name": null,
		"memoed_subtotal": false,
		"candidate_id": null,
		"two_year_transaction_period": 2018,
		"candidate_office_state": null,
		"conduit_committee_name": null
	}, {
		"contributor_employer": "UNIVERSITY OF TEXAS SYSTEMS",
		"contributor_last_name": "MICA",
		"contributor_name": "MICA, CARL B. MR.",
		"candidate_office_district": null,
		"election_type_full": null,
		"contributor_aggregate_ytd": 300.0,
		"unused_contbr_id": null,
		"entity_type": "IND",
		"committee": {
			"candidate_ids": ["H2TX33040"],
			"organization_type": null,
			"city": "AUSTIN",
			"zip": "787091061",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_id": "C00498121",
			"filing_frequency": "Q",
			"organization_type_full": null,
			"designation": "P",
			"street_2": null,
			"state_full": "Texas",
			"street_1": "P.O. BOX 91061",
			"state": "TX",
			"party_full": "REPUBLICAN PARTY",
			"committee_type_full": "House",
			"party": "REP",
			"committee_type": "H",
			"designation_full": "Principal campaign committee",
			"treasurer_name": "FARMER, GARY S.",
			"cycle": 2018,
			"cycles": [2012, 2014, 2016, 2018, 2020]
		},
		"line_number": "12",
		"fec_election_type_desc": "GENERAL",
		"candidate_name": null,
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"file_number": 1298625,
		"amendment_indicator_desc": "ADD",
		"contributor_suffix": null,
		"contributor_state": "TX",
		"candidate_office": null,
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"conduit_committee_state": null,
		"contributor_street_2": null,
		"contributor_occupation": "GOVERNMENT AFFAIRS",
		"conduit_committee_street1": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816168",
		"amendment_indicator": "A",
		"contributor": null,
		"contribution_receipt_date": "2018-11-03T00:00:00",
		"committee_id": "C00498121",
		"contributor_street_1": "12405 VON HERFF CT",
		"schedule_type": "SA",
		"transaction_id": "SA12.11187.83",
		"candidate_last_name": null,
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"report_type": "30G",
		"memo_code_full": null,
		"line_number_label": "Transfers from authorized committees",
		"memo_code": "X",
		"donor_committee_name": null,
		"receipt_type": "15J",
		"candidate_middle_name": null,
		"load_date": "2018-12-20T02:51:49.668000+00:00",
		"contribution_receipt_amount": 300.0,
		"fec_election_year": "2018",
		"contributor_id": null,
		"candidate_office_full": null,
		"image_number": "201812069134816168",
		"conduit_committee_id": null,
		"candidate_suffix": null,
		"contributor_prefix": "MR.",
		"conduit_committee_city": null,
		"contributor_zip": "78732",
		"memo_text": null,
		"report_year": 2018,
		"sub_id": "4121920181622525136",
		"contributor_first_name": "CARL",
		"original_sub_id": null,
		"contributor_middle_name": "B.",
		"back_reference_transaction_id": "SA12.11187",
		"entity_type_desc": "INDIVIDUAL",
		"national_committee_nonfederal_account": null,
		"candidate_prefix": null,
		"increased_limit": null,
		"contributor_city": "AUSTIN",
		"receipt_type_desc": "MEMO (FILER'S % OF CONTRIBUTION GIVEN TO JOIN",
		"back_reference_schedule_name": "SA12",
		"recipient_committee_type": "H",
		"receipt_type_full": "JOINT FUNDRAISER - ROGER FOR CONGRESS VICTORY FUND",
		"is_individual": true,
		"link_id": 4120620181620450055,
		"candidate_first_name": null,
		"conduit_committee_street2": null,
		"committee_name": null,
		"memoed_subtotal": true,
		"candidate_id": null,
		"two_year_transaction_period": 2018,
		"candidate_office_state": null,
		"conduit_committee_name": null
	}, {
		"contributor_employer": "SELF EMPLOYED",
		"contributor_last_name": "KEITH",
		"contributor_name": "KEITH, PATRICK A. MR.",
		"candidate_office_district": null,
		"election_type_full": null,
		"contributor_aggregate_ytd": 1000.0,
		"unused_contbr_id": null,
		"entity_type": "IND",
		"committee": {
			"candidate_ids": ["H2TX33040"],
			"organization_type": null,
			"city": "AUSTIN",
			"zip": "787091061",
			"name": "ROGER WILLIAMS FOR U S CONGRESS COMMITTEE",
			"committee_id": "C00498121",
			"filing_frequency": "Q",
			"organization_type_full": null,
			"designation": "P",
			"street_2": null,
			"state_full": "Texas",
			"street_1": "P.O. BOX 91061",
			"state": "TX",
			"party_full": "REPUBLICAN PARTY",
			"committee_type_full": "House",
			"party": "REP",
			"committee_type": "H",
			"designation_full": "Principal campaign committee",
			"treasurer_name": "FARMER, GARY S.",
			"cycle": 2018,
			"cycles": [2012, 2014, 2016, 2018, 2020]
		},
		"line_number": "11AI",
		"fec_election_type_desc": "GENERAL",
		"candidate_name": null,
		"candidate_office_state_full": null,
		"election_type": "G2018",
		"file_number": 1298625,
		"amendment_indicator_desc": "ADD",
		"contributor_suffix": null,
		"contributor_state": "RI",
		"candidate_office": null,
		"schedule_type_full": "ITEMIZED RECEIPTS",
		"conduit_committee_state": null,
		"contributor_street_2": null,
		"contributor_occupation": "FINANCE",
		"conduit_committee_street1": null,
		"pdf_url": "http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201812069134816141",
		"amendment_indicator": "A",
		"contributor": null,
		"contribution_receipt_date": "2018-11-02T00:00:00",
		"committee_id": "C00498121",
		"contributor_street_1": "17 LEROY AVE.",
		"schedule_type": "SA",
		"transaction_id": "SA11AI.10879",
		"candidate_last_name": null,
		"conduit_committee_zip": null,
		"filing_form": "F3",
		"report_type": "30G",
		"memo_code_full": null,
		"line_number_label": "Contributions From Individuals\/Persons Other Than Political Committees",
		"memo_code": null,
		"donor_committee_name": null,
		"receipt_type": "15",
		"candidate_middle_name": null,
		"load_date": "2018-12-20T02:51:49.663000+00:00",
		"contribution_receipt_amount": 1000.0,
		"fec_election_year": "2018",
		"contributor_id": null,
		"candidate_office_full": null,
		"image_number": "201812069134816141",
		"conduit_committee_id": null,
		"candidate_suffix": null,
		"contributor_prefix": "MR.",
		"conduit_committee_city": null,
		"contributor_zip": "028404105",
		"memo_text": null,
		"report_year": 2018,
		"sub_id": "4121920181622525056",
		"contributor_first_name": "PATRICK",
		"original_sub_id": null,
		"contributor_middle_name": "A.",
		"back_reference_transaction_id": null,
		"entity_type_desc": "INDIVIDUAL",
		"national_committee_nonfederal_account": null,
		"candidate_prefix": null,
		"increased_limit": null,
		"contributor_city": "NEWPORT",
		"receipt_type_desc": "CONTRIBUTION",
		"back_reference_schedule_name": null,
		"recipient_committee_type": "H",
		"receipt_type_full": null,
		"is_individual": true,
		"link_id": 4120620181620450055,
		"candidate_first_name": null,
		"conduit_committee_street2": null,
		"committee_name": null,
		"memoed_subtotal": false,
		"candidate_id": null,
		"two_year_transaction_period": 2018,
		"candidate_office_state": null,
		"conduit_committee_name": null
	}],
	"pagination": {
		"pages": 98,
		"per_page": 10,
		"count": 971,
		"last_indexes": {
			"last_index": "4121920181622525056",
			"last_contribution_receipt_date": "2018-11-02T00:00:00"
		}
	}
}